### ISSUE TITLE
Maybe Is there a problem that when returning by reference.

### ISSUE THREAD

**Issue by imane-jym** [radiotail/eluna#2]
I like eluna very much. I find an issue.
The following code snippet(testInterface.cpp, testInterface.lua):
C++
TestObj& testObjRef(TestObj& p) {  
    p.m_name = "TestObjRef Changed";  
    return p;  
} 
lua
local objRef = TestObj("TestObjRef")  
local a = cppTest:testObjRef(objRef)  
print("testObjRef: ", a, objRef)  
objRef:print()  
a:print()  
output:
testObjRef:     userdata: 0x120b598     userdata: 0x120b538
hello world: TestObjRef Changed [0x120b4f0]
hello world: TestObjRef Changed [0x120b5b0]

I think "objRef:print" should be the same with "a:print".  because testObjRef return a  reference. But It is not same in fact that one's address is 0x120b4f0 and another's address is 0x120b5b0.

**Comment by radiotail** [comment]
Sorry, I see this issue too late.  I have fixed this issue in new version. Thanks.
