### ISSUE TITLE
LuaTable return an default value when the key is not exist. 

### ISSUE THREAD

**Issue by xliangzy** [radiotail/eluna#9]
It will trigger an error when i get a value from LuaTable which key is not exist. 
Return an default value when the key is not exist. 
Is it a good idea? 
Just like this.

	template<>	inline long			read2cpp(lua_State *L, int index) { return (long)luaL_optinteger(L, index, 0);};
	template<>	inline unsigned long  read2cpp(lua_State *L, int index) { return (unsigned long)luaL_optinteger(L, index, 0);};
	template<>	inline long long    read2cpp(lua_State *L, int index) { return (long long)luaL_optinteger(L, index, 0);};
	template<>  inline unsigned long long  read2cpp(lua_State *L, int index) { return (unsigned long long)luaL_optinteger(L, index, 0);};
#endif

	template<>	inline float		read2cpp(lua_State *L, int index) { return (float)luaL_optnumber(L, index, 0.0);};
	template<>	inline double		read2cpp(lua_State *L, int index) { return (double)luaL_optnumber(L, index, 0.0);};
	template<>	inline char*		read2cpp(lua_State *L, int index) { return (char*)luaL_optstring(L, index, ""); };

**Comment by radiotail** [comment]
add "has" method for Luatable in new version
